version: '3.7'

services:
  client:
    container_name: react-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    links:
      - api
    networks:
      - webappnetwork
    stdin_open: true

  api:
    container_name: express-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    networks:
      - webappnetwork
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webappnetwork
    ports:
      - 5432:5432
    
networks:
    webappnetwork:
        driver: bridge